version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
        auth:
          username: bionikspoon
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Run tests
          command: stack --no-terminal test
      - run:
          name: Install executable
          command: stack --no-terminal install
      - save_cache:
          name: Cache Dependencies
          key: v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
